# Site
name: "Anju Gopinath"
title: "Anju Gopinth"
description: "Anju Gopinath."
logo: 'assets/images/favicon.png'
email: anjugopinath@hotmail.com
medium: https://anjugopinath.medium.com/
twitter: https://twitter.com/anjugopinath?lang=en
linkedin: https://www.linkedin.com/in/anjugopinath/
github: https://github.com/anjugopinath
favicon: 'assets/images/favicon.png'
baseurl:
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  anju:
    name: Anju Gopinath
    display_name: Anju Gopinath
    avatar: 'assets/images/avatar.png'
    email: anjugopinath@hotmail.com
    web: https://anjugopinath.medium.com/
    twitter: https://twitter.com/anjugopinath?lang=en

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: 
adsense-data-ad-slot: 

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
